-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 12:56:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema atividade_12
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade_12
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade_12` DEFAULT CHARACTER SET utf8 ;
USE `atividade_12` ;

-- -----------------------------------------------------
-- Table `atividade_12`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_12`.`Professor` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `professor_cpf` CHAR(14) NOT NULL,
  `professor_nome` VARCHAR(255) NOT NULL,
  `professor_data_nasc` DATE NOT NULL,
  `professor_titulacao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`professor_id`),
  UNIQUE INDEX `professor_cpf_UNIQUE` (`professor_cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade_12`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_12`.`Telefone` (
  `telefone_id` INT NOT NULL AUTO_INCREMENT,
  `telefone_numero` CHAR(13) NOT NULL,
  `Professor_professor_id` INT NOT NULL,
  PRIMARY KEY (`telefone_id`),
  INDEX `fk_Telefone_Professor_idx` (`Professor_professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Professor`
    FOREIGN KEY (`Professor_professor_id`)
    REFERENCES `atividade_12`.`Professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade_12`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_12`.`Aluno` (
  `aluno_id` INT NOT NULL AUTO_INCREMENT,
  `aluno_nome` VARCHAR(45) NOT NULL,
  `aluno_endereco` VARCHAR(45) NOT NULL,
  `aluno_telefone` VARCHAR(45) NOT NULL,
  `aluno_data_nasc` VARCHAR(45) NOT NULL,
  `aluno_altura` VARCHAR(45) NULL,
  `aluno_peso` VARCHAR(45) NULL,
  PRIMARY KEY (`aluno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade_12`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_12`.`Turma` (
  `turma_id` INT NOT NULL AUTO_INCREMENT,
  `qtd_alunos` INT NOT NULL,
  `horario` TIME NOT NULL,
  `duracao` TIME NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `curso` VARCHAR(255) NOT NULL,
  `Professor_professor_id` INT NOT NULL,
  `Aluno_monitor_id` INT NOT NULL,
  PRIMARY KEY (`turma_id`),
  INDEX `fk_Turma_Professor1_idx` (`Professor_professor_id` ASC) VISIBLE,
  INDEX `fk_Turma_Aluno1_idx` (`Aluno_monitor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Professor1`
    FOREIGN KEY (`Professor_professor_id`)
    REFERENCES `atividade_12`.`Professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Aluno1`
    FOREIGN KEY (`Aluno_monitor_id`)
    REFERENCES `atividade_12`.`Aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade_12`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_12`.`Matricula` (
  `matricula_id` INT NOT NULL AUTO_INCREMENT,
  `ausencias` INT NULL,
  `matricula_data` DATE NOT NULL,
  `matricula_codigo` VARCHAR(50) NOT NULL,
  `Aluno_aluno_id` INT NOT NULL,
  `Turma_turma_id` INT NOT NULL,
  PRIMARY KEY (`matricula_id`),
  INDEX `fk_Matricula_Aluno1_idx` (`Aluno_aluno_id` ASC) VISIBLE,
  INDEX `fk_Matricula_Turma1_idx` (`Turma_turma_id` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno_aluno_id`)
    REFERENCES `atividade_12`.`Aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Turma1`
    FOREIGN KEY (`Turma_turma_id`)
    REFERENCES `atividade_12`.`Turma` (`turma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
