-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 10:31:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema atividade_10
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade_10
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade_10` DEFAULT CHARACTER SET utf8 ;
USE `atividade_10` ;

-- -----------------------------------------------------
-- Table `atividade_10`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_10`.`Alunos` (
  `aluno_id` INT NOT NULL AUTO_INCREMENT,
  `aluno_nome` VARCHAR(255) NOT NULL,
  `aluno_curso` VARCHAR(255) NOT NULL,
  `aluno_idade` INT NOT NULL,
  PRIMARY KEY (`aluno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade_10`.`Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_10`.`Turmas` (
  `turma_id` INT NOT NULL AUTO_INCREMENT,
  `turma_nome` VARCHAR(255) NOT NULL,
  `turma_sala` VARCHAR(255) NOT NULL,
  `turma_horario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`turma_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade_10`.`Matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_10`.`Matriculas` (
  `matricula_id` INT NOT NULL,
  `nota_1` DECIMAL(5,2) NOT NULL,
  `nota_2` DECIMAL(5,2) NOT NULL,
  `nota_3` DECIMAL(5,2) NOT NULL,
  `nota_final` DECIMAL(5,2) NOT NULL,
  `nr_faltas` INT NULL,
  `Alunos_aluno_id` INT NOT NULL,
  `Turmas_turma_id` INT NOT NULL,
  PRIMARY KEY (`matricula_id`),
  INDEX `fk_Matriculas_Alunos_idx` (`Alunos_aluno_id` ASC) VISIBLE,
  INDEX `fk_Matriculas_Turmas1_idx` (`Turmas_turma_id` ASC) VISIBLE,
  CONSTRAINT `fk_Matriculas_Alunos`
    FOREIGN KEY (`Alunos_aluno_id`)
    REFERENCES `atividade_10`.`Alunos` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matriculas_Turmas1`
    FOREIGN KEY (`Turmas_turma_id`)
    REFERENCES `atividade_10`.`Turmas` (`turma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

