-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 11:45:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema atividade_11
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade_11
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade_11` DEFAULT CHARACTER SET utf8 ;
USE `atividade_11` ;

-- -----------------------------------------------------
-- Table `atividade_11`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_11`.`Comanda` (
  `comanda_id` INT NOT NULL AUTO_INCREMENT,
  `comanda_data` DATE NOT NULL,
  `comanda_nr_mesa` INT NOT NULL,
  `comanda_nome_cliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`comanda_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade_11`.`Cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_11`.`Cardapio` (
  `cardapio_id` INT NOT NULL AUTO_INCREMENT,
  `cardapio_cafe_nome` VARCHAR(100) NOT NULL,
  `cardapio_descricao` TEXT NULL,
  `cardapio_preco_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`cardapio_id`),
  UNIQUE INDEX `cardapio_cafe_nome_UNIQUE` (`cardapio_cafe_nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade_11`.`Item_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade_11`.`Item_comanda` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_quantidade` INT NOT NULL,
  `Comanda_comanda_id` INT NOT NULL,
  `Cardapio_cardapio_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_Item_comanda_Comanda_idx` (`Comanda_comanda_id` ASC) VISIBLE,
  INDEX `fk_Item_comanda_Cardapio1_idx` (`Cardapio_cardapio_id` ASC) VISIBLE,
  UNIQUE INDEX `Cardapio_cardapio_id_UNIQUE` (`Cardapio_cardapio_id` ASC) VISIBLE,
  UNIQUE INDEX `Comanda_comanda_id_UNIQUE` (`Comanda_comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_comanda_Comanda`
    FOREIGN KEY (`Comanda_comanda_id`)
    REFERENCES `atividade_11`.`Comanda` (`comanda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_comanda_Cardapio1`
    FOREIGN KEY (`Cardapio_cardapio_id`)
    REFERENCES `atividade_11`.`Cardapio` (`cardapio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
